spring:
  datasource:
    password: root
    url: jdbc:postgresql://localhost:5432/inventory
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true